stages:
  threatfox_fetch:
    cmd: python src/data/threatfox_fetch.py
    deps:
      - src/data/threatfox_fetch.py
    outs:
      - data/raw/threatfox.json

  preprocess:
    cmd: python src/data/preprocess_data.py
    deps:
      - src/data/preprocess_data.py
      - data/raw/Merged63.csv
      - data/raw/threatfox.json
    outs:
      - data/preprocessed/normal.csv
      - data/preprocessed/attacks.csv
      - data/preprocessed/threats.csv

  validate:
    cmd: cd gx && python run_checkpoints.py
    deps:
      - data/preprocessed/normal.csv
      - data/preprocessed/attacks.csv
      - data/preprocessed/threats.csv
    outs:
      - gx:
          persist: true
    
  test:
    cmd: python src/tests/tests.py
    deps:
      - src/tests/tests.py
      - data/preprocessed/threats.csv
    outs:
      - reports/data_testing_report.html:
          persist: true
      - data/reference/threats.csv:
          persist: true