name: Fetch, Preprocess, Validate

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python getting ready
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Configure DVC
        run: |
          dvc remote modify origin --local access_key_id ${{ secrets.DAGSHUB_ACCESS_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DAGSHUB_SECRET_ACCESS_KEY }}
      
      - name: Install DVC S3
        run: pip install 'dvc[s3]'

      - name: Run DVC pipeline
        run: |
          dvc pull --force
          dvc status
          dvc repro
          dvc push
          git add dvc.lock
          git commit -m "Update dvc.lock on `date` with GitHub Actions" || true
        env:
          THREATFOX_API_KEY: ${{ secrets.THREATFOX_API_KEY }}

      - name: Commit changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add dvc.lock
          git commit -m "Update dvc.lock $(date)" || echo "No changes"
          git push
